<a href="https://colab.research.google.com/github/jihye-jeon2/python/blob/main/pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Series시리즈와 DataFrame데이터프레임

In [ ]:
import pandas as pd

In [ ]:
#시리즈 만들기  리스트형태로 넣어주면 됨
s=pd.Series(['apple','banana']) #파이썬 리스트(list)를 pd.Series()함수에 전달하면 리스트 각요소가 시리즈의 데이터가 된
display(s)

0     apple
1    banana
dtype: object

In [ ]:
s=pd.Series(data=['Wes Mckinney', 'Creator of Pandas'], index=['Person','Who'])   #인덱스를 숫자가 아닌 이름으로 지정 ㄱ
display(s)

Person         Wes Mckinney
Who       Creator of Pandas
dtype: object

In [ ]:
#데이터프레임 만들기
scientists =pd.DataFrame(
    data={
    "Occupation":["Chemist","Statistician"],
    "Born":["1920-07-25","1876-06-13"],
    "Died":["1958-04-16","1937-10-16"],
    "Age":[37,61]

},
    index=["Rosaline Franklin","William Gosset"],
    columns=["Occupation","Born","Died","Age"]
)
display(scientists)

                     Occupation        Born        Died  Age
Rosaline Franklin       Chemist  1920-07-25  1958-04-16   37
William Gosset     Statistician  1876-06-13  1937-10-16   61

In [ ]:
first_row=scientists.loc["William Gosset"]
print(type(first_row))  #Series형태
display(first_row)  #인덱스와 값으로 이루어진 시리즈

<class 'pandas.core.series.Series'>

Occupation    Statistician
Born            1876-06-13
Died            1937-10-16
Age                     61
Name: William Gosset, dtype: object

In [ ]:
print(first_row.index)

Index(['Occupation', 'Born', 'Died', 'Age'], dtype='object')

In [ ]:
#시리즈의 keys() 메서드 : 인덱스의 목록 반환  Series -> 인덱스와 값만 존재해서
#데이터프레임에서의 keys() 메서드:키 목록을 반환
print(first_row.keys())  #시리즈에서는 인덱스나 키나 똑같은 결과

Index(['Occupation', 'Born', 'Died', 'Age'], dtype='object')

In [ ]:
print(first_row.index[0])

Occupation

TypeError: 'method' object is not subscriptable

In [ ]:
scientists=pd.read_csv("/content/drive/MyDrive/kwu (1)/빅데이터/pandas_ex/Data/scientists.csv")

In [ ]:
display(scientists)
display(scientists.describe())
display(scientists.info())

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

             Age
count   8.000000
mean   59.125000
std    18.325918
min    37.000000
25%    44.000000
50%    58.500000
75%    68.750000
max    90.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      object
 1   Born        8 non-null      object
 2   Died        8 non-null      object
 3   Age         8 non-null      int64
 4   Occupation  8 non-null      object
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes

None

In [ ]:
ages=scientists["Age"]
display(ages)

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [ ]:
print(ages.describe())
print(ages.mean())

count     8.000000
mean     59.125000
std      18.325918
min      37.000000
25%      44.000000
50%      58.500000
75%      68.750000
max      90.000000
Name: Age, dtype: float64
59.125

In [ ]:
print(ages[ages > ages.mean()])  #True 에 해당되는것만 리스트로 반환

1    61
2    90
3    66
7    77
Name: Age, dtype: int64

In [ ]:
print(ages>ages.mean())

0    False
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: Age, dtype: bool

##벡터와 스칼라
#벡터(vector):순서가 있는 여러 개의 값들의 집합을 의미, 수학적으로는 1차원 배열,pandas에서는 시리즈(Series)가 벡터이다.<br>
#스칼라(Scalar):하나의 단일값을 의미

In [ ]:
display(ages)
display(type(ages))

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

pandas.core.series.Series

In [ ]:
print(ages+ages)

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

In [ ]:
print(ages*ages)

0    1369
1    3721
2    8100
3    4356
4    3136
5    2025
6    1681
7    5929
Name: Age, dtype: int64

In [ ]:
print(ages+100)  #벡터 + 스칼라

0    137
1    161
2    190
3    166
4    156
5    145
6    141
7    177
Name: Age, dtype: int64

In [ ]:
print(ages*2)

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

In [ ]:
#길이가 서로다른 벡터 연산하기  #시리즈ages는 값이 8개, 새로만든 시리즈는 값이 2개
print(ages+pd.Series([1,100]))
#오류는 안나지만...

0     38.0
1    161.0
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
dtype: float64

In [ ]:
import numpy as np

In [ ]:
print(ages+ np.array([1,100])) # array 행렬,리스트  오류..길이안맞음이

ValueError: operands could not be broadcast together with shapes (8,) (2,)

In [ ]:
#인덱스가 같은 벡터 자동 정렬하기
rev_ages= ages.sort_index(ascending=False)  #내림차순
display(rev_ages)

7    77
6    41
5    45
4    56
3    66
2    90
1    61
0    37
Name: Age, dtype: int64

In [ ]:
print(ages+rev_ages) #같은 인덱스 값을계산

0     74
1    122
2    180
3    132
4    112
5     90
6     82
7    154
Name: Age, dtype: int64

###데이터프레임

In [ ]:
display(scientists)

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [ ]:
scientists.index

RangeIndex(start=0, stop=8, step=1)

In [ ]:
scientists.columns

Index(['Name', 'Born', 'Died', 'Age', 'Occupation'], dtype='object')

In [ ]:
scientists.values #값들을확인, 한행의 값이 2차원배열의 형태로해서[[]]

array([['Rosaline Franklin', '1920-07-25', '1958-04-16', 37, 'Chemist'],
       ['William Gosset', '1876-06-13', '1937-10-16', 61, 'Statistician'],
       ['Florence Nightingale', '1820-05-12', '1910-08-13', 90, 'Nurse'],
       ['Marie Curie', '1867-11-07', '1934-07-04', 66, 'Chemist'],
       ['Rachel Carson', '1907-05-27', '1964-04-14', 56, 'Biologist'],
       ['John Snow', '1813-03-15', '1858-06-16', 45, 'Physician'],
       ['Alan Turing', '1912-06-23', '1954-06-07', 41,
        'Computer Scientist'],
       ['Johann Gauss', '1777-04-30', '1855-02-23', 77, 'Mathematician']],
      dtype=object)

In [ ]:
print(scientists['Age'].mean())

59.125

In [ ]:
print(scientists.loc[scientists['Age']>scientists['Age'].mean()]) #True값에해당되는 행만(loc)뽑아라

In [ ]:
#데이터프레임으로 연산하기
first_half = scientists[:4]  #첨부터 3
second_half = scientists[4:]  #4부터 끝
print(first_half)
print(second_half)

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist
            Name        Born        Died  Age          Occupation
4  Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5      John Snow  1813-03-15  1858-06-16   45           Physician
6    Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7   Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [ ]:
print(scientists * 2) #각 값에 2배 곱하기 문자열*2 -> 문자열 문자열

                                       Name                  Born  \
0        Rosaline FranklinRosaline Franklin  1920-07-251920-07-25
1              William GossetWilliam Gosset  1876-06-131876-06-13
2  Florence NightingaleFlorence Nightingale  1820-05-121820-05-12
3                    Marie CurieMarie Curie  1867-11-071867-11-07
4                Rachel CarsonRachel Carson  1907-05-271907-05-27
5                        John SnowJohn Snow  1813-03-151813-03-15
6                    Alan TuringAlan Turing  1912-06-231912-06-23
7                  Johann GaussJohann Gauss  1777-04-301777-04-30

                   Died  Age                            Occupation
0  1958-04-161958-04-16   74                        ChemistChemist
1  1937-10-161937-10-16  122              StatisticianStatistician
2  1910-08-131910-08-13  180                            NurseNurse
3  1934-07-041934-07-04  132                        ChemistChemist
4  1964-04-141964-04-14  112                    BiologistBiologist
5  1858-06-161858-06-16   90                    PhysicianPhysician
6  1954-06-071954-06-07   82  Computer ScientistComputer Scientist
7  1855-02-231855-02-23  154            MathematicianMathematician

In [ ]:
df1 =df2 = pd.DataFrame(data=[[1,2,3],[4,5,6],[7,8,9]])
display(df1)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df_added = df1.add(df2)
display(df_added)

    0   1   2
0   2   4   6
1   8  10  12
2  14  16  18

###시리즈와 데이터프레임 데이터 변경하기

In [ ]:
#object가 pandas 문법에서는 string문자열 형인가봄..

In [ ]:
 #datetime()날짜형태로 바꿔주는 함수

###열 내용 변경하기

In [ ]:
print(scientists['Age'])

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [ ]:
print(scientists["Age"].sample(frac=1,random_state=42))
#frac=1 frac 인자는 샘플링할 비율을 지정, 전체데이터(100%)를 샘플링하겟다는 의미,
#모든 데이터를 포함하되 순서만 무작위로 섞는 (셔플링) 효과를 줍니다
#random_state인자는 난수생성기의 시드(seed)를 설정,
# 이 값을 지정하면 코드를 여러번 실행해도 항상 동일한 순서로 데이터가 섞이게된다.(=결과의 재현성을 보장한다)

1    61
5    45
0    37
7    77
2    90
4    56
3    66
6    41
Name: Age, dtype: int64

In [ ]:
scientists["Age"]=scientists["Age"].sample(frac=1,random_state=42)  #섞기 전이랑 동일함
print(scientists['Age'])

0    37
1    61
2    90
3    66
4    56
5    45
6    41
7    77
Name: Age, dtype: int64

In [ ]:
from typing import ValuesView
scientists["Age"] = scientists["Age"].sample(frac=1,random_state=42).values
print(scientists['Age'])

0    61
1    45
2    37
3    77
4    90
5    56
6    66
7    41
Name: Age, dtype: int64

###데이터 프레임에서 행 삭제하기

In [ ]:
scientists.set_index('Name')  #Name컬럼값으로 데이터프레임의 행 인덱스 설정해줌

                            Born        Died  Age          Occupation
Name
Rosaline Franklin     1920-07-25  1958-04-16   61             Chemist
William Gosset        1876-06-13  1937-10-16   45        Statistician
Florence Nightingale  1820-05-12  1910-08-13   37               Nurse
Marie Curie           1867-11-07  1934-07-04   77             Chemist
Rachel Carson         1907-05-27  1964-04-14   90           Biologist
John Snow             1813-03-15  1858-06-16   56           Physician
Alan Turing           1912-06-23  1954-06-07   66  Computer Scientist
Johann Gauss          1777-04-30  1855-02-23   41       Mathematician

In [ ]:
display(scientists.head())

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   61       Chemist
1        William Gosset  1876-06-13  1937-10-16   45  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   37         Nurse
3           Marie Curie  1867-11-07  1934-07-04   77       Chemist
4         Rachel Carson  1907-05-27  1964-04-14   90     Biologist

In [ ]:
scientists_without_franklin=scientists.drop(index=['Rosaline Franklin'])  #한행만 삭제된 데이터프레임을 보여줌

KeyError: "['Rosaline Franklin'] not found in axis"

In [ ]:
scientists.set_index('Name', inplace=True)
scientists_without_multiple = scientists.drop(index=['Rosaline Franklin', 'William Gosset'])

In [ ]:
#apply() 함수   데이터프레임.apply(함수)
#.dt는 시리즈의 날짜/시간 관련 속성에 접근하게 해준다
#.days 는 day정보만 정수로 추출한다
#.dt.days 로 숫자로 변경
display(scientists.head())

KeyError: 'age_days'

In [ ]:
#assign() 함수로 열 수정하기
#apply() 이 시리즈의 각 값에 대해 특정함수를 적용하고 싶을 때 사용
#assign() 기존 데이터프레임을 변경하지 않고 새로운 열이 추가되거나 변경된 새로운 데이터프레임을 반환
#괄호안에는 새로 생성할 열의 이름과 그값을 지정

In [ ]:
#필요없는열,행 삭제